server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:3001/postgres
    driverClassName: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
email:
  api-key: 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
  sender-email: no-reply@formulari.io
  sender-name: Formulari
  