server:
  port: ${PORT:3000}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:3001/postgres}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_GENERATE_DDL:update}
email:
  api-key: ${BREVO_API_KEY}
  sender-email: no-reply@formulari.io
  sender-name: Formulari
# App Properties
app:
  jwtCookieName: formulari
  jwtSecret: ${JWT_SECRET}
  # 1h = 60 * 60 * 1000
  jwtExpirationMs: 3600000
logging.level.org.springframework: WARN