server:
  port: ${PORT:3000}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:3001/postgres}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_GENERATE_DDL:update}
email:
  api-key: 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
  sender-email: no-reply@formulari.io
  sender-name: Formulari
# App Properties
app:
  jwtCookieName: formulari
  jwtSecret: OQRx6zRwJGYeH1ErSc9D9rmW74pHEoig1xIK8frN8QJOy850nK2AWMu3Ei3kdDL
  jwtExpirationMs: 86400000